### ISSUE TITLE
Can't load currently airing

### ISSUE THREAD

**Issue by favtan** [littleweeb/Desktop#16]
It just says loading currently airing forever.

**Comment by EldinZenderink** [comment]
I would suggest you to join discord, you can find out why it's not loading as well as a troubleshooting guide. Here is an invite: https://discord.gg/5rCAhVQ , But just to be short, one of the information providers is currently struggling for funds (https://kitsu.io). Since LittleWeeb fully relies on kitsu.io for it's information about anime (including currently airing), it can't fetch the information anymore and thus doesn't load anything. (Although, this issue did occur in the past, unrelated to kitsu but that should've been solved long ago).

**Comment by favtan** [comment]
I tried the troubleshooting guide in the discord but it still doesn't work.
