### ISSUE TITLE
Web based version and question

### ISSUE THREAD

**Issue by bonny1992** [littleweeb/Desktop#2]
Hi! I want to start this with some compliments to you: this software looks extremely interesting!

Will be there a chance to see it with a web based version?

Also a little question: in what language does LittleWeeb download the anime?
Because as a man of culture I prefer the subs to the dubs, but I don't know if this will search for my language!

**Comment by EldinZenderink** [comment]
Due to the limitations of the browsers and having no in browser video player that supports embedded subtitles in mkv's it wont be possible on a short term. I am however interested in the webassembly so in the future... who knows. Language wise I cant tell. Mostly english. Mostly sub. I don't manage the content found by littleweeb. The files are found using the api from https://nibl.co.uk and there is not really a way to tell what language is used by looking at the filename unless they specify it. That said, about 90% of the currently airing comes from horriblesubs since they release the fastest. 

Hope that answers your questions.

**Comment by bonny1992** [comment]
@EldinZenderink 
Thank you for your fast reply!
I understand, that's a pity, but thank you anyway!

**Comment by DumbJoe** [comment]
Is there a way to filter results dubs from subs or vice versa?

**Comment by DumbJoe** [comment]
Maybe the program can read the meta data/tags and figure out whether the episodes are in English or Japanese with subs (or without if you understand Jap fluently...)?
