### ISSUE TITLE
Stuck on "Retrieving synonyms"

### ISSUE THREAD

**Issue by tannasnod** [littleweeb/Desktop#3]
None of the episodes are loading for me, currently airing isn't loading for me, and I have no idea what to do.

**Comment by EldinZenderink** [comment]
Ok, weird. Which version, which platform (operating system), which anime?

**Comment by tannasnod** [comment]
Odd, now it's working. Must have been an error on my end.

**Comment by EldinZenderink** [comment]
Indeed weird, but if it's working now, i am going to close this issue. If it happens again, you can reopen it.

**Comment by NezhaIsTrap** [comment]
Hi, I have a similar issue.
Whenever I try to look for "currently airing" or search for anything, it just gives me the "loading currently airing text" or "searching and the circle loads forever

I accidentally installed the developer build[ (293) v0.4.0 ] before I installed the release [ (302) v0.4.0 ] if it helps with anything, and they both have the same problem. Back End and IRC are connected

**Comment by EldinZenderink** [comment]
@NezhaIsTrap Currently the source where littleweeb retrieves its information from; https://kitsu.io is having issues and is currently not reachable (since yesterday). See https://twitter.com/HeyKitsu/status/1108081618273607680 . Seems to be a big issue for it to be gone for so long (its a first for me since the release of littleweeb). Unfortunately this is a third party which I hold no influence over, and I haven't implemented a fallback to other third party sources such as mal or anilist (yet). So LittleWeeb will remain borderline useless for the time being, until kitsu fixes it or I finally come around to finishing the new version, and add as a addition another information source.

**Comment by NezhaIsTrap** [comment]
@EldinZenderink Well that sucks.
Anyways nice work you've done from what I've seen, I'll try again when the source is up again.

**Comment by Bigdoggies** [comment]
I'm having the same issue although it seems Kitsu is working properly.

**Comment by ShadowDoctorK** [comment]
I also have the issue that has been described above. Ver 0.4.0 Build 302. I just downloaded the client today from the website.

![image](https://user-images.githubusercontent.com/33364380/61454757-c8dd1580-a92f-11e9-91ca-cd1ea76a7f9c.png)

**Comment by lukizel** [comment]
Same problem. Windows 10 Home x64 1903, 0.4.0 302
