### ISSUE TITLE
unable to connect to back-end

### ISSUE THREAD

**Issue by sshawnsamuell** [littleweeb/Desktop#7]
out of the blue, littleweeb on startup gets stuck in the connecting to back-end screen. unfortunately, the loading popup that takes over the program essentially locks me out of the program, as it immediately pops back up if I try to close the message, so I am unable to enable any of the debugging options in the settings window. I have tried deleting every file associated with littleweeb, uninstalling, rebooting pc, switching VPN ips, disabling vpn, disabling firewalls with no luck.

Can only assume this is an issue with connecting on my end, but my network knowledge is basically none.

**Comment by EldinZenderink** [comment]
Hi, can you specify which OS? Even if the step in the issue reporting guide cannot be done, it would help if you'd try the following steps and report whether theses steps can be done or not.

**Comment by MT0DE** [comment]
Got the same problem with my LittleWeeb (Windows 10). 
Haven't been able to use it since last Saturday, but haven't really tried anything to fix the problem(?) except to reinstall it. Didn't do anything. However, I noticed that my internet speed dropped dramatically to almost 500 Kbps (and yes, I am not kidding) when downloading episodes, unlike the 32 Mbps download speed I had since the beginning (from when I downloaded LittleWeeb)

**Comment by EldinZenderink** [comment]
There is only one factor that might affect download speeds. Go to you Documents -> Littleweeb -> DebugLog and open the log file, if the size isn't to large, then proceed to delete the content. In littleweeb  -> settings uncheck every debug option if not already unchecked. If however it seems like you can't open the log file, you might have to delete the entire LittleWeeb directory. The issues is due to littleweeb having a memory leak ish where it keeps track of every line within the debug log, not much of a problem for a few thousand, but when the log file starts to exceed a certain amount of lines it has to keep track of all of them, and apparently that is quit resource intensive and sometimes limits the speed at which it can download. This will be (is already) fixed with the still in development upcomming version (but unfortunately due to time resources being VERY limited, I can't promise  a release date.)

Another cause can be the source you download from. With source I mean the selected bot. If the bot maintainer decides he doesnt want to spend money on a fast file server, your going to notice that in your speed. You can select the bot when you click on advanced  on the anime page. 

Bots i would recommend, if available: Ginpachi-Sensei (8-9 Mb/s == 90mbps), CR-X (Most of them are really fast, it maxes out my internet at 25 Mb/s == 200 Mbps, but on my VPS with a gigabit link I reach 100 Mb/s (1000 mbps) once. Or Arutha seems decent as well. Can't say for others.

If neither fixes your problem, I can't help you since the problem probably lies outside littleweeb. Better test with speedtest.net or something similar in combination with some network troubleshooting.

**Comment by MT0DE** [comment]
Thank you! It works properly again!
The problem was, as mentioned, the debug log (Size: 11 MB).  Removing the debug file opened up LittleWeeb in seconds. Though this is a rather small problem, I appreciate that you responded within ONE hour (unlike some tech support services) and also mentioned some tips for downloading future episodes. Hope you will get more spare time to work on LittleWeeb 2.0!
